### ISSUE TITLE
Setgid / Setuid does not work on go1.6.linux-amd64

### ISSUE THREAD

**Issue by FeNoMeNa** [bradfitz/runsit#6]
I have noticed a strange behavior when I've run the e2e test. The registered test daemon was not run with the following error:

```
11:05:00.581584 runsit.go:126: Task "daemon1"/1457946300-pid30429: Task exited; err=exit status 1
11:05:05.583837 runsit.go:126: Task "daemon1"/1457946305-pid30437: Task exited; err=&{2016-03-14 11:05:05.583305511 +0200 EET stderr 2016/03/14 11:05:05 failed to Setuid(1000): operation not supported false 0xc8201c03c0}
```

The problems is related with setting of ```gid``` / ```uid```:

```go
	if lr.Gid != 0 {
		if err := syscall.Setgid(lr.Gid); err != nil {
			log.Fatalf("failed to Setgid(%d): %v", lr.Gid, err)
		}
	}
```

```go
	if lr.UID != 0 {
		if err := syscall.Setuid(lr.UID); err != nil {
			log.Fatalf("failed to Setuid(%d): %v", lr.UID, err)
		}
	}
```

I should mention that this bug is noticed only on go1.6.linux-amd64.

We have tested with other architectures and versions of Go, the results are:
```
go1.5.3.linux-amd64 - there is no bug
go1.6.darwin-amd64 - there is no bug
```

**Comment by bradfitz** [comment]
runsit is unmaintained and it's recommended you don't use it.

I've updated the text at https://github.com/bradfitz/runsit
